apiVersion: apps/v1
kind: Deployment
metadata:
  name: kme-shelloperator
  namespace: kme
  labels: 
    name: kme-shelloperator
    app: kme-shelloperator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kme-shelloperator
  template:
    metadata:
      labels: 
        name: kme-shelloperator
        app: kme-shelloperator
    spec:
      serviceAccountName: 
      containers:
        - name: shelloperator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50Mi
{{- if .Values.imagePullSecret }}      
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}